### ISSUE TITLE
custom enrichers for journals & rich text

### ISSUE THREAD

**Issue by Lyinggod** [Lyynix/MoreJournalEnrichers#13]
The ability to define text or a pattern that occurs in a journal or rich text field and the text that will be replaced, along with the ability to store multiple criteria.

Example
Search: [ad]
replace: <span class>a</span>

**Comment by Lyynix** [comment]
I have implemented this feature (I hope this is what you were requesting) and it is coming with the 1.2.0 release
What I implemented is the ability to add multiple key-value-pairs, which can be used in your journal with @​Var[key] and will be replaced by the corresponding value in the journal
