### ISSUE TITLE
Add an enricher to include the contents of an existing page

### ISSUE THREAD

**Issue by elespike** [Lyynix/MoreJournalEnrichers#14]
Hello,

Would it be possible to create an enricher, such as `@Page`, that would include the contents of an existing page onto a separate journal entry?

For example, page A would have some content like:
```
hello I'm page A
```

And page B wants to not only reference page A, but repeat its contents inline so that:
```
this is page B, it's a cool page
@Page[<page A's ID>]
```
becomes:
```
this is page B, it's a cool page
hello I'm page A
```

And then, whenever the content of page A is updated, it automatically updates on page B as well.

**Comment by Lyynix** [comment]
Hey, Thank you for your feature request!

I think, that this is possible. Ill look into it, and if it is, its gonna be added to the module :)

**Comment by elespike** [comment]
Awesome, thanks! I can probably help, just not familiar with the foundry API yet.

**Comment by Lyynix** [comment]
So, i have implemented this feature for text, image and video pages, and it will be part of the 1.3.0 release
I have not implemented the pdf page yet, this might be added with a later update tho (depending on demand)

If you want (and know how) you can download the [page-enricher](https://github.com/Lyynix/MoreJournalEnrichers/tree/page-enricher) branch and test the feature before official release

**Comment by elespike** [comment]
Outstanding, thanks very much! I'll give it a shot.
