### ISSUE TITLE
@Page[] enricher in Actor notes

### ISSUE THREAD

**Issue by tcm151** [Lyynix/MoreJournalEnrichers#22]
**Is your feature request related to a problem? Please describe.**
Using the @Page[] enricher in an Actor's notes does not insert the linked journal page.

**Describe the solution you'd like**
It would be really great if this worked. I have journal entries for all my NPC characters, and I'd like to insert that page into their Actor notes so it can easily be see in both places.

**Comment by Lyynix** [comment]
Hey, I'm sorry for the late response. I'll look into that as soon as I'm able to work on LMJE again, thank you for your bugreport!

**Comment by Lyynix** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [P1: @Page[] doesn't work in Character Sheets](https://trello.com/c/7oiHqMCb/52-p1-page-doesnt-work-in-character-sheets)
