### ISSUE TITLE
Multiple @IfChecked causes problems

### ISSUE THREAD

**Issue by maxobremer** [Lyynix/MoreJournalEnrichers#38]
**Describe the bug**
I was making a puzzle where certain details can be swapped in and out and multiple @IfChecked would not render properly

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a test world and make a journal entry like the one attached to this [fvtt-JournalEntry-puzzle-test-IuYv8Xo3uWZhL1MM.json](https://github.com/user-attachments/files/17174771/fvtt-JournalEntry-puzzle-test-IuYv8Xo3uWZhL1MM.json)
2. See that the enrichers havent rendered right
![image](https://github.com/user-attachments/assets/a9b8a9d8-f037-49e1-80b8-77627e1452bb)

**Expected behaviour**
to render properly where the unchecked values are not visible and the checked ones are, like this: 
![image](https://github.com/user-attachments/assets/a0d67c2e-6be2-4179-9f03-5ba4bd15002c)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Foundry v12.331 DnD5e V3.3.1
 - Version [e.g. 22] MoreJournalEnrichers 1.2.1

**Additional context**
Good work on the module so far

**Comment by Lyynix** [comment]
Thanks for the bug report, i'll take a look asap!

**Comment by Lyynix** [comment]
should be fixed in [1.3.2](https://github.com/Lyynix/MoreJournalEnrichers/releases/download/v1.3.2/module.json) :)
notify me if thats not the case

**Comment by maxobremer** [comment]
Works like a charm now. To build onto this, would it be possible to have a feature that makes checkboxes become unable to be clicked if specific other checkboxes have been clicked? If you look in the example picture of my original message, the dm can pick a name for each column, but it would be nice if selecting lets say Alex in the first column blocks out Alex in the other columns as well as the names Brent and Cedric in the first column.

What do you think of this functionality?

**Comment by Lyynix** [comment]
This sounds like what you want are [radio-buttons](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio)?
While clicking through your journal i did think about adding more logical enrichers like radio-buttons, but also a "NotChecked" as a negation of the "IfChecked"
Hower I think that might need a bit of a rework internally and I can't promise a ETA for that feature
