### ISSUE TITLE
Error while updating (missing file)

### ISSUE THREAD

**Issue by sirgawain111** [Lyynix/MoreJournalEnrichers#7]
**Describe the bug**
When I'm trying to update the module, I get an error (see screenshot) because of a missing file.

**To Reproduce**
Try to update the module version 0.3.0.

**Screenshots**
![image](https://github.com/Lyynix/MoreJournalEnrichers/assets/85822812/db83009c-cb75-42f6-a60f-b1c96c6c55b3)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 117.0.5938.92
 - Foundry version 11.308
 - Module version: 0.3.0

**Comment by Lyynix** [comment]
should be fixed in 0.3.1
